SCAN = "scan"
BUILD = "build"
SEARCH = "search"
RECALL = "recall"
EMERGENCY = "emergency"

CONNECTED = "connected"

QUIT = "quit"

DISCONNECT = "disconnect"

MAP_HIDDEN_STATES = [DISCONNECT, SCAN]

SWARM_COMMANDS = [BUILD, SEARCH, RECALL, EMERGENCY, DISCONNECT]